task 3: data integration, cleaning & Preprocessing with pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
a = pd.read_csv(r"C:\Users\Skaynet\Desktop\DA project1\datasets\customer_churn.csv")
a.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [3]:
a.shape

(440833, 12)

In [4]:
print(a.shape[0])
a.shape[1]

440833

12

In [5]:
a.info()

<class 'pandas.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  str
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  str
 8   Contract Length    440832 non-null  str
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), str(3)
memory usage: 40.4 MB

In [6]:
a.describe()

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn
count,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000
mean,225398.667955,39.373153,31.256336,15.807494,3.604437,12.965722,631.616223,14.480868,0.567107
std,129531.918550,12.442369,17.255727,8.586242,3.070218,8.258063,240.803001,8.596208,0.495477
min,2.000000,18.000000,1.000000,1.000000,0.000000,0.000000,100.000000,1.000000,0.000000
25%,113621.750000,29.000000,16.000000,9.000000,1.000000,6.000000,480.000000,7.000000,0.000000
50%,226125.500000,39.000000,32.000000,16.000000,3.000000,12.000000,661.000000,14.000000,1.000000
75%,337739.250000,48.000000,46.000000,23.000000,6.000000,19.000000,830.000000,22.000000,1.000000
max,449999.000000,65.000000,60.000000,30.000000,10.000000,30.000000,1000.000000,30.000000,1.000000

In [7]:
a.isnull().sum()

CustomerID           1
Age                  1
Gender               1
Tenure               1
Usage Frequency      1
Support Calls        1
Payment Delay        1
Subscription Type    1
Contract Length      1
Total Spend          1
Last Interaction     1
Churn                1
dtype: int64

In [8]:
a.isnull().sum().sum()

np.int64(12)

In [9]:
a[a.isnull().all(axis=1)]

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
199295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
print("Completely blank rows")
a.isnull().all(axis=1).sum()

Completely blank rows

np.int64(1)

In [11]:
a.dropna(how="all",inplace=True)
a.shape

(440832, 12)

Checking for duplicate records

In [12]:
print("number of duplicated rows :")
a.duplicated().sum()

number of duplicated rows :

np.int64(0)

In [13]:
a.columns

Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency',
       'Support Calls', 'Payment Delay', 'Subscription Type',
       'Contract Length', 'Total Spend', 'Last Interaction', 'Churn'],
      dtype='str')

In [14]:
a.columns=(a.columns.str.strip().str.lower().str.replace(" ","_"))

a.rename(columns={'customerid':'customer_id', 'age':'age', 'gender':'gender', 'tenure':'tenure', 'usagefrequency':"usage_frequency",
       'supportcalls':'support_calls', 'paymentdelay':"payment_delay", 'subscriptiontype':'subscription_type', 'contractlength':'contract_length',
       'totalspend':'total_spend', 'lastinteraction':'last_interaction', 'churn':'churn'},inplace=True)
a.columns.str.strip().str.lower()
a.columns

Index(['customer_id', 'age', 'gender', 'tenure', 'usage_frequency',
       'support_calls', 'payment_delay', 'subscription_type',
       'contract_length', 'total_spend', 'last_interaction', 'churn'],
      dtype='str')

Changing Datatypes

In [15]:
a.dtypes

customer_id          float64
age                  float64
gender                   str
tenure               float64
usage_frequency      float64
support_calls        float64
payment_delay        float64
subscription_type        str
contract_length          str
total_spend          float64
last_interaction     float64
churn                float64
dtype: object

In [16]:
# changing from float column tointeger column 
integer_column=['customer_id', 'age', 'tenure', 'usage_frequency',
       'support_calls', 'payment_delay', 'last_interaction', 'churn','total_spend']
for col in integer_column:
    print(col)
    a[col]=pd.to_numeric(a[col],errors="coerce")

for col in integer_column:
    a[col]=a[col].round().astype("int64")

text_clmn=[ 'gender','subscription_type',
'contract_length']   
for col in text_clmn:
    a[col]=a[col].astype("string").str.strip().str.title()
print(a.dtypes)

customer_id
age
tenure
usage_frequency
support_calls
payment_delay
last_interaction
churn
total_spend
customer_id           int64
age                   int64
gender               string
tenure                int64
usage_frequency       int64
support_calls         int64
payment_delay         int64
subscription_type    string
contract_length      string
total_spend           int64
last_interaction      int64
churn                 int64
dtype: object

In [17]:

print("minimum age",a["age"].min())
print("maximum age",a["age"].max())
a["age"].describe()

minimum age 18
maximum age 65

count    440832.000000
mean         39.373153
std          12.442369
min          18.000000
25%          29.000000
50%          39.000000
75%          48.000000
max          65.000000
Name: age, dtype: float64

In [18]:
print(a["tenure"].min())
print(a["tenure"].max())

1
60

In [19]:
print(a["total_spend"].min())
print(a["total_spend"].max())

100
1000

In [20]:
# replacing churn values from 0,1 to no,yes respectively
a["churn"]=a["churn"].astype("string")
a["churn"]=a["churn"].replace({"1":"Yes","0":"no"})
a.tail()

,customer_id,age,gender,tenure,usage_frequency,support_calls,payment_delay,subscription_type,contract_length,total_spend,last_interaction,churn
440828,449995,42,Male,54,15,1,3,Premium,Annual,716,8,no
440829,449996,25,Female,8,13,1,20,Premium,Annual,745,2,no
440830,449997,26,Male,35,27,1,5,Standard,Quarterly,977,9,no
440831,449998,28,Male,55,14,2,0,Standard,Quarterly,603,2,no
440832,449999,31,Male,48,20,1,14,Premium,Quarterly,568,21,no

In [21]:
a["churn"].value_counts()

churn
Yes    249999
no     190833
Name: count, dtype: Int64

Detecting Outliers using IQR

In [22]:
for col in a.columns:
    if a[col].dtype=="int64":
        print(col)
    else :
        0

customer_id
age
tenure
usage_frequency
support_calls
payment_delay
total_spend
last_interaction

In [25]:
numeric_columns=("customer_id","age","tenure","usage_frequency","support_calls","payment_delay","total_spend","last_interaction")
for col in numeric_columns:
    Q1=a[col].quantile(0.25)
    Q3=a[col].quantile(0.75)
    IQR=Q3-Q1
    lower=Q1-1.5*IQR
    upper=Q3+1.5*IQR
    outliers= a[(a[col]<lower) |
                 (a[col]>upper)]
    print(col,"outliers:",len(outliers))

customer_id outliers: 0
age outliers: 0
tenure outliers: 0
usage_frequency outliers: 0
support_calls outliers: 0
payment_delay outliers: 0
total_spend outliers: 0
last_interaction outliers: 0

In [56]:
# Feature engineering
# creating a new column for spend_per_tenure and high_support_flag
a["spend_per_tenure"]=((a["total_spend"]/ a["tenure"]).round(2).astype(float))
a["high_support_flag"]=(a["support_calls"]>=7).astype("string")
a["high_support_flag"]=a["high_support_flag"].replace({"True":"Yes","False":"no"})

In [57]:
a.head()

,customer_id,age,gender,tenure,usage_frequency,support_calls,payment_delay,subscription_type,contract_length,total_spend,last_interaction,churn,spend_per_tenure,high_support_flag
0,2,30,Female,39,14,5,18,Standard,Annual,932,17,Yes,23.90,no
1,3,65,Female,49,1,10,8,Basic,Monthly,557,6,Yes,11.37,Yes
2,4,55,Female,14,4,6,18,Basic,Quarterly,185,3,Yes,13.21,no
3,5,58,Male,38,21,7,7,Standard,Monthly,396,29,Yes,10.42,Yes
4,6,23,Male,32,20,5,8,Basic,Monthly,617,20,Yes,19.28,no

Final Cleaning Validation

In [59]:
print("Duplicate Rows :",a.duplicated().sum())
print("Final Shape :",a.shape)
print("Total Missing Values :",a.isnull().sum().sum())
print("\nData Types :")
print(a.dtypes)

Duplicate Rows : 0
Final Shape : (440832, 14)
Total Missing Values : 0

Data Types :
customer_id            int64
age                    int64
gender                string
tenure                 int64
usage_frequency        int64
support_calls          int64
payment_delay          int64
subscription_type     string
contract_length       string
total_spend            int64
last_interaction       int64
churn                 string
spend_per_tenure     float64
high_support_flag     string
dtype: object

In [61]:
a.to_csv("clean_dataset.csv",index=False)

In [63]:
import os
print(os.path.exists("clean_dataset.csv"))

True

In [68]:
## before vs after cleaning csv
comparison=pd.DataFrame({
    "checks":["rows",
"columns",
"missing values",
"blank rows",
"duplicate rows",
"data types",
"feature engineering"
             ],
    "before":[
        "440833",
        "12",
        "12",
        "1",
        "0",
        "inconsistent",
        "No"
    ],
    "After":[
        "440832",
        "14",
        "0",
        "0",
        "0",
        "stanardized",
        "Yes"
    ]
})
print(comparison)

                checks        before        After
0                 rows        440833       440832
1              columns            12           14
2       missing values            12            0
3           blank rows             1            0
4       duplicate rows             0            0
5           data types  inconsistent  stanardized
6  feature engineering            No          Yes